name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL}}
jobs:
  test-and-deploy:
      name: check database and run test 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: migration database
          run: |
            sudo apt-get install libpq-dev -y
            cargo install sqlx-cli
            sqlx migrate run
        - uses: actions-rs/cargo@v1
          with:
            command: test
            # args: --release --all-features
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only