name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  APP_ENVIRONMENT: production
  app_TEST: testword
jobs:
  # database-migration:
  #     name: Database migration
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions-rs/toolchain@v1
  #         with:
  #           toolchain: stable
  #       - name: Migrate database
  #         run: |
  #           sudo apt-get install libpq-dev -y
  #           cargo install sqlx-cli
  #           sqlx migrate run
  test:
      # needs: database-migration
      name: Test app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - uses: actions-rs/cargo@v1
          with:
            command: test
  # deploy:
  #     needs: test
  #     name: Deploy app
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v3
  #       - uses: superfly/flyctl-actions/setup-flyctl@master
  #       - run: flyctl deploy --remote-only